apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: d75yp3u0m-nodejs
  janus-idp.io/tekton: d75yp3u0m-nodejs
  backstage.io/kubernetes-id: d75yp3u0m-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: d75yp3u0m-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
